### PR TITLE
Improve error message printing

### LINKED ISSUE #42: Improve error messages
Some error messages are not shown to the user

1. `ce` in https://github.com/OpenEnergyPlatform/oem2orm/blob/bbb6511a1d46d7fc9ebdd390258202a5e7fdbaf6/oem2orm/oep_oedialect_oem2orm.py#L121-L124

2. `null` in type field results in internal server error, 

Reproduce with:
Metadata [meta_dat.json](https://github.com/OpenEnergyPlatform/oem2orm/files/14497047/meta_dat.json)
Error msg:

```
    if item.split(" ")[-1] == "array":
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

https://github.com/OpenEnergyPlatform/oem2orm/blob/bbb6511a1d46d7fc9ebdd390258202a5e7fdbaf6/oem2orm/oep_oedialect_oem2orm.py#L206-L211

### PR DESCRIPTION
**Pull request by chrwm**
Solves observed error 1:
Adds `ce` to error message printing.

I couldn't solve error 2 from the issue.

Closes #42

### CODE REVIEW

**Comment by henhuy** [comment]
Added fix for second error

**Review by henhuy — APPROVED** [review]

**Comment by henhuy** [comment]
@jh-RLI could you review as well and start integrating this version into OEP if everything looks good?
Would be a big improvement for user experience...

**Comment by jh-RLI** [comment]
oem2orm is not yet really integrated into the oep. The functionality to create a table via the metadata could be part of the table creation via Api & Ui Wizzard, but it is not. I think to integrate the error message we would have to implement this in the oedialect. Or just catch the error in the oep and output it when a table is created. I would have to check again which error we catch and return in the oep. We may just never return the error if it is triggered via the api based table creation.

**Comment by jh-RLI** [comment]
I can do a new release for oem2orm and publish this version on pypi.

**Pull request merged**
